[package]
name = "scannerprog"
version = "0.1.1"
authors = ["stuart"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.45"
dioxus = { version = "0.7.10", features = ["router", "desktop"] }
dirs = "7.0.0"
rfd = "0.17.2"
ron = "0.12.2"
serde = { version = "1.0.229", features = ["derive"] }
serialport = { version = "4.10.1", default-features = false }
tokio = { version = "1.53.2", features = ["time", "rt", "sync"] }

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]


[lints.clippy]
# Safety and Correctness
unwrap_used = "deny"
expect_used = "deny"
print_stdout = "deny"
print_stderr = "deny"

# Code Quality (Pedantic/Restriction)
pedantic = { level = "warn", priority = -1 }
clone_on_ref_ptr = "warn"
dbg_macro = "warn"
exit = "warn"
unused_result_ok = "warn"

# Allowances for Pedantic Group (to reduce noise)
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"