[application]

[bundle]
publisher = "Inner-Marker"
identifier = "com.innermarker-scannerprog"
icon = [ # dx bundle picks the right format for each platform from this list
  "assets/sp-icons/icon-32.png",     # Small sizes for Linux menus/taskbars
  "assets/sp-icons/icon-128.png",
  "assets/sp-icons/128x128@2x.png",  # HiDPI variant
  "assets/sp-icons/icon.icns",       # macOS app bundle icon
  "assets/sp-icons/icon.ico",        # Windows executable/installer icon
]
[web.app]

# HTML title tag content
title = "scannerprog"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
