[application]

[bundle]
publisher = "Inner-Marker"
identifier = "com.innermarker-scannerprog"
icon = [
  "assets/sp-icons/icon-128.png",
  "assets/sp-icons/icon.icns",
  "assets/sp-icons/icon.ico",
]
[web.app]

# HTML title tag content
title = "scannerprog"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
